[package]
name = "feed-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.188"
futures = "0.3.28"
tokio = {version = "1.32.0", features = ["full"]}
urlencoding = "2.1.3"
chrono = "0.4.41"

[dependencies.mongodb]
version = "3.2.4"
